baseURL = 'https://blog.fuga.jp/'
languageCode = 'ja-jp'
title = '思いつきそうで思いつかなくていたときに'
theme = 'PaperMod'
copyright = 'Copyright(c) 2022,2023 SATO Daisuke. All rights reserved.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      codeFences = true
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = true
      noClasses = true
      style = "modus-vivendi"
      tabWidth = 4
  [author]
  name = 'SATO Daisuke'
